# Generated by Django 5.2.4 on 2025-08-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_about_me_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpData',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Email')),
                ('otp', models.CharField(blank=True, max_length=10, null=True, verbose_name='One Time Password')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
