# Generated by Django 5.2.4 on 2025-08-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_project_is_unique_alter_project_is_verified_and_more'),
        ('Users', '0004_otpdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_project',
            field=models.ManyToManyField(through='Projects.ProjectLike', to='Projects.project', verbose_name='Liked Project'),
        ),
    ]
