# Generated by Django 5.1.7 on 2025-03-31 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_descriptions', models.TextField(default='--No descriptions--', max_length=100)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=50)),
                ('label_descriptions', models.TextField(default='--No descriptions--', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=15, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('project_external_image', models.TextField(blank=True, max_length=400, null=True)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=150)),
                ('project_use_count', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('Last_update', models.DateField(auto_now=True)),
                ('project_status', models.CharField(default='Comming Soon')),
                ('project_document_file', models.FileField(blank=True, null=True, upload_to=None)),
                ('project_url', models.URLField(blank=True, default='/url-not-found', null=True)),
                ('project_github_repo', models.URLField(blank=True, default='/url-not-found', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.projectcategory')),
            ],
        ),
    ]
