# Generated by Django 5.2.4 on 2025-08-04 15:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField(max_length=150)),
                ('user_username', models.CharField(max_length=30)),
                ('use_count', models.IntegerField(default=0)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('Last_update', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Comming Soon')),
                ('is_verified', models.BooleanField(default=False)),
                ('document_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('deployed_url', models.URLField(blank=True)),
                ('github_repository', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('descriptions', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('descriptions', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Project Label',
                'verbose_name_plural': 'Project Labels',
                'ordering': ['name'],
            },
        ),
    ]
