# Generated by Django 5.1.7 on 2025-03-21 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_descriptions', models.TextField(max_length=100)),
                ('category_use_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=150)),
                ('project_use_count', models.IntegerField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('project_document_file', models.FileField(blank=True, null=True, upload_to=None)),
                ('project_url', models.URLField()),
                ('category', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='Projects.projectcategory')),
                ('user', models.ForeignKey(default='Anonymus', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['project_name'],
            },
        ),
    ]
