# Generated by Django 5.1.7 on 2025-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdetail',
            options={},
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='Last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='project_github_repo',
            field=models.URLField(default='Comming Soon'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='project_status',
            field=models.CharField(default='Comming Soon'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_url',
            field=models.URLField(default='Comming Soon'),
        ),
    ]
