# Generated by Django 5.2.4 on 2025-08-05 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='framework',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='handle',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectcatalog',
            name='handle',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectlabel',
            name='handle',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ProjectCatalog', to='Projects.projectcatalog'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='label',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ProjectLabel', to='Projects.projectlabel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
