# Generated by Django 5.2 on 2025-04-06 07:20

import Projects.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='category',
            field=models.ForeignKey(default=Projects.models.setDefaultCategory, on_delete=django.db.models.deletion.SET_DEFAULT, to='Projects.projectcategory'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='label',
            field=models.ForeignKey(default=Projects.models.setDefaultLabel, on_delete=django.db.models.deletion.SET_DEFAULT, to='Projects.projectlabel'),
        ),
    ]
