# Generated by Django 5.1.7 on 2025-03-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_projectdetail_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='category_use_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_github_repo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_image',
            field=models.ImageField(blank=True, max_length=350, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_use_count',
            field=models.IntegerField(default=0),
        ),
    ]
