# Generated by Django 5.2.4 on 2025-08-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_framework_project_handle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcatalog',
            options={'ordering': ['name'], 'verbose_name': 'Project Catalog', 'verbose_name_plural': 'Project Catalogs'},
        ),
        migrations.AlterField(
            model_name='projectcatalog',
            name='handle',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='handle',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
