# Generated by Django 5.2.4 on 2025-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_alter_projectcatalog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verification Status(True/False)'),
        ),
        migrations.AlterField(
            model_name='projectcatalog',
            name='handle',
            field=models.CharField(editable=False, max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projectlabel',
            name='handle',
            field=models.CharField(editable=False, max_length=75, null=True, unique=True),
        ),
    ]
