# Generated by Django 5.1.7 on 2025-03-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_alter_projectcategory_category_use_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='project_External_image',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
