# Generated by Django 5.1.7 on 2025-03-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_projectdetail_project_external_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetail',
            old_name='project_External_image',
            new_name='project_external_image',
        ),
    ]
