# Generated by Django 5.2.4 on 2025-08-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_video',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='deployed_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_repository',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
