# Generated by Django 5.1.7 on 2025-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_rename_project_external_image_projectdetail_project_external_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='nickname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
