# Generated by Django 5.2.4 on 2025-08-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_project_demo_video_alter_project_deployed_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='use_count',
            new_name='view_count',
        ),
    ]
