# Generated by Django 5.1.7 on 2025-03-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_projectdetail_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='project_github_repo',
            field=models.URLField(blank=True, default='/url-not-found', null=True),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_url',
            field=models.URLField(blank=True, default='/url-not-found', null=True),
        ),
    ]
