# Generated by Django 5.2.4 on 2025-08-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_rename_use_count_project_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='catalog',
        ),
    ]
