# Generated by Django 5.2.4 on 2025-08-09 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_rename_category_project_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_unique',
            field=models.BooleanField(default=False, verbose_name='Unique Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verification Status'),
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Liked Date&Time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='user_liked',
            field=models.ManyToManyField(blank=True, through='Projects.ProjectLike', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
    ]
