# Generated by Django 5.2.4 on 2025-08-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_descriptions', models.TextField(default='No Descriptions', max_length=250)),
                ('blog_external_image', models.TextField(max_length=400)),
                ('blog_like', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
