# Generated by Django 5.1.7 on 2025-03-31 08:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_descriptions', models.TextField(default='No Descriptions', max_length=250)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('blog_external_image', models.TextField(max_length=400)),
                ('blog_like', models.IntegerField(default=0)),
                ('blog_comments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=100), blank=True, default=list, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
