# Generated by Django 5.1.7 on 2025-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_one', models.TextField(max_length=400)),
                ('image_two', models.TextField(max_length=400)),
                ('image_three', models.TextField(max_length=400)),
            ],
        ),
    ]
